name: SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        
    - name: Cache SonarCloud dependencies
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonarcloud-${{ hashFiles('**/*.py') }}
        restore-keys: |
          ${{ runner.os }}-sonarcloud-

    - name: Run SonarCloud Scanner
      uses: sonarsource/sonarcloud-github-action@v1
      with:
        organization: vaishnavikolavasi18  # Replace with your SonarCloud organization key
        projectKey: VaishnaviKolavasi_PythonProject     # Replace with your project key
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Add your SonarCloud token to GitHub Secrets
